### ISSUE TITLE
USER STORY: Bio Section

### ISSUE THREAD

**Issue by DiarmuidSheeran** [DiarmuidSheeran/whats-cooking-social-site#1]
**As a registered user, I can include a bio section so that I can share some personal details about me.**. 🧑‍🦲  

# Description: 

-  Implement the ability for users to view and update their profile bio. ❓ 

## Tasks:

- [ ] Create a bio editing form. ✏️ 
- [ ] Update the database to store and retrieve user bios.✏️
- [ ] Add bio section to users profile page. ✏️
