### ISSUE TITLE
USER STORY: User Registration and Authentication

### ISSUE THREAD

**Issue by DiarmuidSheeran** [DiarmuidSheeran/whats-cooking-social-site#10]
**As a site user I can login or create an account and logout so that I can view my content and other users content and choose to logout when finished.** :smiley:

# Description:

- Create a user registration page that allows users to sign up with their email and password.  :question:

## Tasks:

- [ ] Design and implement the registration form. :pencil2:
- [ ]  Implement user validation and error handling. :pencil2:
- [ ]  Store user information in the database. :pencil2:
