### ISSUE TITLE
USER STORY: Like Posts

### ISSUE THREAD

**Issue by DiarmuidSheeran** [DiarmuidSheeran/whats-cooking-social-site#12]
**As a registered user, I can like or unlike posts so that I can interact with the content. of the site to enhance my experience.**🧑‍🦲  

# Description: 

-  Implement the functionality for users to like and unlike posts. ❓ 

## Tasks:

- [ ] Create a like button on posts. ✏️ 
- [ ] Update the database to store and retrieve the like counts.✏️
- [ ] Implement a likes count on post. ✏️
