### ISSUE TITLE
USER STORY: Update or delete user information

### ISSUE THREAD

**Issue by DiarmuidSheeran** [DiarmuidSheeran/whats-cooking-social-site#13]
**As a registered user, I can edit or delete my profile information so that I can keep my personal information up to date and delete it if necessary** 🧑‍🦲  

# Description: 

-  Implement the ability for users to view update or delete their  profile information. ❓ 

## Tasks:

- [ ] Create a information editing form. ✏️ 
- [ ] Update the database to store and retrieve users information.✏️
- [ ] Add "Edit Account" option in user settings. ✏️ 
- [ ] Add a "Delete Account" option in user settings. ✏️ 
- [ ] Ensure users data is cleaned from database ✏️
