### ISSUE TITLE
USER STORY: Update posts

### ISSUE THREAD

**Issue by DiarmuidSheeran** [DiarmuidSheeran/whats-cooking-social-site#16]
**As a registered user, I can  update my posts so that I can edit or delete my content.** 🧑‍🦲  

# Description: 

-  Enable users to  update or delete their own posts. ❓ 

## Tasks:

- [x] Create a post edit form. ✏️ 
- [x] Update the database to store and retrieve the updated user posts.✏️
- [x] Implement a edit button on individual posts. ✏️ 
- [x] Implement a delete button on individual posts. ✏️ 
- [x] Ensure that only the post creator can delete their posts. ✏️
